routes/dashboard.php
<?php

use App\Http\Controllers\Dashboard\AdminController;
use App\Http\Controllers\Dashboard\AgentController;
use App\Http\Controllers\Dashboard\ContactController;
use App\Http\Controllers\Dashboard\CouponController;
use App\Http\Controllers\Dashboard\FatwaController;
use App\Http\Controllers\Dashboard\HomeController;
use App\Http\Controllers\Dashboard\ManskController;
use App\Http\Controllers\Dashboard\NotificationController;
use App\Http\Controllers\Dashboard\OptionController;
use App\Http\Controllers\Dashboard\OrderController;
use App\Http\Controllers\Dashboard\PageController;
use App\Http\Controllers\Dashboard\SettingController;
use App\Http\Controllers\Dashboard\ShopController;
use App\Http\Controllers\Dashboard\ShopItemController;
use App\Http\Controllers\Dashboard\SliderController;
use App\Http\Controllers\Dashboard\UmrahPackageController;
use App\Http\Controllers\Dashboard\UmrahRequestsController;
use App\Http\Controllers\Dashboard\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
//  */
// Route::middleware('guest:admin')->group(function () {

//    Route::get('/login', [AuthController::class, 'login'])->name('login');
//    Route::post('/login', [AuthController::class, 'submitLogin'])->name('submit-login');
// });

Auth::routes([
    'register' => false,
    'reset' => true,
    'verify' => false,
]);

Route::middleware(['auth:admin', 'is_active'])->group(function () {

    Route::get('/', HomeController::class)->name('home');

    //Settings
    Route::get('/settings/create', [SettingController::class, 'create'])->name('settings.create');
    Route::post('/settings/store', [SettingController::class, 'store'])->name('settings.store');
    /* CONTACT US MESSAGE ACTIONS */
    Route::post('/messages/{contact}/read', [\App\Http\Controllers\Dashboard\ContactController::class,'read'])->name('contacts.read');
    Route::post('/messages/{contact}/replied', [\App\Http\Controllers\Dashboard\ContactController::class,'replied'])->name('contacts.replied');
    Route::get('/notifications', [NotificationController::class,'index'])->name('notifications.index');
    Route::get('/notifications/{notification}', [NotificationController::class,'show'])->name('notifications.show');







    //Toggle
    Route::post('/admins/{admin}/toggle', [AdminController::class, 'toggle'])->name('admins.toggle');

    Route::post('/pages/{page}/toggle', [PageController::class, 'toggle'])->name('pages.toggle');

    Route::post('/options/{option}/toggle', [OptionController::class, 'toggle'])->name('key.options.toggle');

    Route::post('/sliders/{slider}/toggle', [SliderController::class, 'toggle'])->name('sliders.toggle');
    Route::delete('options/{option}/destroy', [OptionController::class, 'destroy'])->name('key.options.destroy');


    //Resources
    Route::resource('contacts', ContactController::class)->only(['show','index','destroy']);
    Route::resource('admins', AdminController::class)->except(['show']);
    Route::resource('pages', PageController::class)->except(['show']);

    Route::resource('key.options', OptionController::class)->except(['show', 'destroy']);
    Route::resource('sliders', SliderController::class)->except(['show']);
});

routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

app/Http/Controllers/Dashboard/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Datatables\AdminDatatable;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\AdminRequest;
use App\Models\Admin;

class AdminController extends Controller
{
    public function index()
    {
        if(request()->ajax())
        {
            return AdminDatatable::getData();
        }
        return view('dashboard.admins.index');
    }
    public function store(AdminRequest $request)
    {
        Admin::create($request->validated());

        return redirect()->route('dashboard.admins.index')->with('success', __('translate.created_successfully'));
    }
    public function create()
    {
        return view('dashboard.admins.create');
    }


    public function edit(Admin $admin)
    {
        return view('dashboard.admins.edit', compact('admin'));
    }
     public function update(AdminRequest $request, Admin $admin)
    {
        $data = $request->validated();
        if(!$data['password']){
            unset($data['password']);
        }
        $admin->update($data);

        return redirect()->route('dashboard.admins.index')->with('success', __('translate.updated_successfully'));
    }

    public function destroy(Admin $admin)
    {
        if($admin->email == "admin@app.com"){
            return response()->json([
                'message' => __('translate.cant_delete_admin')
            ], 403);
        }
        $admin->delete();
        return response()->json([
            'message' => __('translate.deleted_successfully')
        ]);
    }

    public function toggle(Admin $admin)
    {

        if($admin->email == "admin@app.com"){
            return response()->json([
                'message' => __('translate.cant_toggle_admin')
            ], 403);
        }
        if($admin->id == auth()->id()){
            return response()->json([
                'message' => __('translate.cant_toggle_yourself')
            ], 403);
        }

        $admin->is_active = !$admin->is_active;
        $admin->save();

        return response()->json([
            'message' => __('translate.updated_successfully')
        ]);
    }
}

app/Http/Controllers/Dashboard/ContactController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Datatables\ContactDatatable;
use App\Http\Controllers\Controller;
use App\Http\Requests\ContactRequest;
use App\Http\Resources\OptionResource;
use App\Models\Contact;
use Illuminate\Support\Str;

class ContactController extends Controller
{

    public function index()
    {
        if(request()->ajax()){
            return (new ContactDatatable(new Contact))->getData();
        }
        return view('dashboard.contacts.index');
    }
    public function show(Contact $contact)
    {
        return view('dashboard.contacts.show',compact('contact'));
    }

    public function destroy(Contact $contact)
    {
        $contact->delete();
        return response()->json([
            'message' => __('translate.deleted_successfully'),
        ]);
    }

    public function read(Contact $contact)
    {
        $contact->update([
            'is_read' => !$contact->is_read,
        ]);
        return redirect()->back()->with('success', __('translate.updated_successfully'));
    }
    public function replied(Contact $contact)
    {
        $contact->update([
            'is_replied' => !$contact->is_replied,
        ]);
        return redirect()->back()->with('success', __('translate.updated_successfully'));
    }






}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function __invoke()
    {

        return view('dashboard.home');

    }
}

app/Http/Controllers/Dashboard/NotificationController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Datatables\AdminDatatable;
use App\Datatables\NotificationDatatable;
use App\Http\Controllers\Controller;
use App\Models\AdminNotification;

class NotificationController extends Controller
{
    public function index()
    {
        if(request()->ajax()){
            return (new NotificationDatatable(new AdminNotification))->getData();
        }
        return view('dashboard.notifications.index');
    }

    public function show(AdminNotification $notification)
    {
        if(!$notification->read_at){
            $notification->update(['read_at' => now(),'read_by' => auth()->id()]);
        }
        return redirect($notification->link);
    }

    public function markAsRead(AdminNotification $notification)
    {
        $notification->update(['read_at' => now()]);

        return response()->json([
            'status' => true,
//            'message' => __('notifications.marked_as_read'),
        ]);
    }
}

app/Http/Controllers/Dashboard/OptionController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Datatables\OptionDatatable;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\OptionRequest;
use App\Http\Requests\Dashboard\ShopRequest;
use App\Models\Option;
use Illuminate\Http\Request;

class OptionController extends Controller
{
    private $datatable;

    public function __construct(private $model = null, private $viewsDomain = null , OptionDatatable  $datatable = null)
    {
        $this->model = new Option();
        $this->datatable = $datatable;
        $this->viewsDomain = 'dashboard.options.';

    }

    private function view($view, $params = [])
    {
        return view($this->viewsDomain . $view, $params);
    }

    /**
     * Display a listing of the resource.
     */
    public function index($key)
    {
        if(request()->ajax()){

        return $this->datatable->getData($key);

        }

        return $this->view('index' , compact('key'));

    }

    /**
     * Show the form for creating a new resource.
     */
    public function create($key)
    {

        return $this->view('create' , compact('key'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store($key,OptionRequest $request)
    {

        $data=array_merge($request->validated() , ['key' => $key] ) ;
        $this->model->create($data);

        return redirect(route('dashboard.key.options.index' , compact('key')))->with('success', __('translate.created_successfully'));
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($key,Option $option)
    {

        return $this->view('edit', compact('key' , 'option'));

    }

    /**
     * Update the specified resource in storage.
     */
    public function update(OptionRequest $request,$key , Option $option)
    {
        $option->update($request->validated());
        return redirect(route('dashboard.key.options.index' , compact('key')))->with('success', __('translate.updated_successfully'));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Option $option)
    {
        $option->delete();
        return response()->json([
            'message' => __('translate.deleted_successfully')
        ]);
    }

    public function toggle(Option $option, Request $request)
    {
        $option->update([
            $request->property => $request->value,
        ]);
        return response()->json([
            'message' => __('translate.updated_successfully')
        ]);


    }
}

app/Http/Controllers/Dashboard/PageController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Datatables\PageDatatable;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\PageRequest;
use App\Models\Page;
use Illuminate\Http\Request;

class PageController extends Controller
{
    public function index()
    {
        if(request()->ajax())
        {
            return (new PageDatatable(new Page))->getData();
        }
        return view('dashboard.pages.index');
    }

    public function create()
    {
        return view('dashboard.pages.create');
    }

    public function store(PageRequest $request)
    {
        Page::create($request->validated());

        return redirect()->route('dashboard.pages.index')->with('success', __('translate.added_successfully'));
    }

    public function edit(Page $page)
    {
        return view('dashboard.pages.edit', compact('page'));
    }

    public function update(PageRequest $request, Page $page)
    {
        $page->update($request->validated());

        return redirect()->route('dashboard.pages.index')->with('success', __('translate.updated_successfully'));
    }

    public function destroy(Page $page)
    {
        $page->delete();

        return response()->json([
            'message' => __('translate.deleted_successfully')
        ]);
    }

    public function order(Page $page)
    {
        //
    }

    public function toggle(Page $page)
    {
        $page->update(['is_active' => !$page->is_active]);

        return response()->json([
            'message' => __('translate.updated_successfully')
        ]);
    }
}

app/Http/Controllers/Dashboard/SettingController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    public function create()
    {if (request()->has('page')) {
        $page = request('page');
    } else {
        return abort(404);
    }
        $options = Setting::with(['translations' , 'media'])->where('page', $page)->get();
        return view('dashboard.settings.create', ['options' => $options, 'page' => $page]);
    }
    public function store(Request $request)
    {
        $settings = Setting::with(['translations' , 'media'])->get();
        abort_if($settings->isEmpty(), 404);

        foreach ($request->all() as $key => $item) {
            $this->processSetting($key, $item, $settings);
        }
        return redirect()->back()->with('success', __('translate.updated_successfully'));
    }

    private function processSetting($key, $item, $settings)
    {
        $setting = $settings->where('key', $key)->first();
        if (!$setting) {
            return;
        }
        if (in_array($setting->type, ['image', 'video']) && $this->hasFile($key, 'image')) {
            $this->storeMedia($setting, $key);
        } else {
            $setting->update($item);

        }
    }
    private function hasFile($key, $type)
    {

        return request()->hasFile("{$key}.{$type}");
    }

    private function storeMedia($setting, $key)
    {
        $setting->clearMediaCollection('settings');

        $fileKey = "{$key}.image";
        $filename = $setting->value . '.' . request()->file($fileKey)->getClientOriginalExtension();

        $setting->addMediaFromRequest($fileKey)
            ->usingFileName($filename)
            ->toMediaCollection('settings');
    }

}

app/Http/Controllers/Dashboard/SliderController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Datatables\SliderDatatable;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\SliderRequest;
use App\Models\Slider;
use Illuminate\Http\Request;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        if(request()->ajax())
        {
            return (new SliderDatatable(new Slider()))->getData();
        }
        return view('dashboard.sliders.index');
    }

    public function create()
    {
        return view('dashboard.sliders.create');
    }

    public function store(SliderRequest $request)
    {
        Slider::create($request->validated());

        return redirect()->route('dashboard.sliders.index')->with('success', __('translate.added_successfully'));
    }

    public function edit(Slider $slider)
    {
        return view('dashboard.sliders.edit', compact('slider'));
    }

    public function update(SliderRequest $request, Slider $slider)
    {
        $slider->update($request->validated());
        if($request->has('image')){

        $slider->storeMediaFromRequest();
        }
        return redirect()->route('dashboard.sliders.index')->with('success', __('translate.updated_successfully'));
    }

    public function destroy(Slider $slider)
    {
        $slider->delete();

        return response()->json([
            'message' => __('translate.deleted_successfully')
        ]);
    }
    public function toggle(Slider $slider, Request $request)
    {
        $slider->update([
            $request->property => $request->value,
        ]);

        return response()->json([
            'message' => __('translate.updated_successfully')
        ]);
    }


}

resources/views/dashboard/admins/create.blade.php
@extends('dashboard.layouts.master')

@php($route='admins')

@section('title', __('translate.create') .' ' . __('translate.'.Str::singular($route) ))

@section('breadcrumbs', Breadcrumbs::render('resource'))
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form class="row g-3 " action="{{route('dashboard.admins.store')}}" method="post" >
                        @csrf
                        <x-flash_message/>
                        <x-forms.input label="name" name="name" type="text"  error_name="name"/>
                        <x-forms.input label="email" name="email" type="email"  error_name="email"/>
                        <x-forms.input label="phone" name="phone" type="text"  error_name="phone"/>
                        <x-forms.input label="password" name="password" type="password"  error_name="password"/>
                        <x-forms.input label="password_confirmation" name="password_confirmation" type="password" :required=false error_name="password_confirmation"/>
                        <x-forms.submit value="create"/>
                    </form>


                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->
@endsection

resources/views/dashboard/admins/edit.blade.php
@extends('dashboard.layouts.master')

@php($route='admins')

@section('title', __('translate.edit') .' ' . __('translate.'.Str::singular($route) ))

@section('breadcrumbs', Breadcrumbs::render('resource'))

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form class="row g-3" action="{{ route('dashboard.admins.update', $admin->id) }}"
                        method="post">
                        @csrf
                        @method('PUT')
                        <x-forms.input label="name" name="name" type="text" error_name="name"
                            value="{{ $admin->name }}" />
                        <x-forms.input label="email" name="email" type="email" error_name="email"
                            value="{{ $admin->email }} " />
                        <x-forms.input label="phone" name="phone" type="text" error_name="phone"
                            value="{{ $admin->phone }} " />
                        <x-forms.input label="password" name="password" type="password" :required=false
                            error_name="password" />
                        <x-forms.input label="password_confirmation" name="password_confirmation"
                            :required=false type="password" :required=false
                            error_name="password_confirmation" />
                        <x-forms.submit value="update" />
                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->
@endsection

resources/views/dashboard/admins/index.blade.php
@extends('dashboard.layouts.master')

@php($route='admins')

@section('title', __('translate.'.$route))

@section('breadcrumbs', Breadcrumbs::render('resource'))

@section('css')
    <link rel="stylesheet" type="text/css" href="{{ URL::asset('assets/libs/datatables/datatables.min.css') }}">
@endsection

@section('action')
    <button class="btn btn-primary  dropdown-toggle" type="button"
            onclick="location.href='{{ route("dashboard.{$route}.create") }}'">
        <i class="mdi mdi-plus"></i> @lang('translate.create')
    </button>
@endsection

<x-datatable.delete :$route/>


@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">


                    <table id="datatable" class="table table-bordered dt-responsive nowrap"
                           style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th> @lang('translate.name')</th>
                            <th> @lang('translate.email')</th>
                            <th> @lang('translate.phone')</th>
                            <th> @lang('translate.is_active')</th>
                            <th> @lang('translate.created_at')</th>
                            <th> @lang('translate.action')</th>

                        </tr>
                        </thead>


                        <tbody>

                        </tbody>
                    </table>

                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->
@endsection

@push('scripts')
    <!-- Required datatable js -->
    <script src="{{ asset('assets/libs/datatables/datatables.min.js') }}"></script>

    <!-- Datatable init js -->
    {{-- <script src="{{URL::asset('assets/js/pages/datatables.init.js')}}"></script> --}}

    <script src="{{ URL::asset('assets/js/app.js') }}"></script>
    <script>
        let datatableUrl = '{{ route("dashboard.{$route}.index") }}';
    </script>
    <script>
        $(document).ready(function() {

            let table = $('#datatable').DataTable({
                "language": {
                    "url": $('#importLangLocal').attr('data-LangLocal'),

                },
                serverSide: true,
                ajax: {
                    url: datatableUrl,
                },
                columns: [
                    { data: 'DT_RowIndex', name: 'DT_RowIndex', searchable: false, orderable: false },
                    {
                        data: 'name',
                        name: 'name',
                        searchable: true,
                        sortable: true
                    },{
                        data: 'email',
                        name: 'email',
                        searchable: true,
                        sortable: true
                    },{
                        data: 'phone',
                        name: 'phone',
                        searchable: true,
                        sortable: true
                    },
                    {
                        data: 'is_active',
                        name: 'is_active',
        //                 render: function(data, type, full, meta) {
        //                     return `
        // <div class="form-check form-switch">
        //     <input type="checkbox" class="form-check-input toggle-is-active"  data-property="is_active" data-id="${full.id}" ${data == 1 ? 'checked' : ''}>
        // </div>`;
        //                 },

                        searchable: true,
                        sortable: true
                    },

                    {
                        data: 'created_at',
                        name: 'created_at',
                        searchable: false
                    },
                    {
                        data: 'actions',
                        name: 'actions',
                        searchable: false,
                        sortable: false
                    }
                ],

            });
        });

        $('#datatable').on('change', '.toggle-is-active', function() {
            var recordId = $(this).data('id');
            var isActive = $(this).prop('checked');
            var property = $(this).data('property');
            var value = isActive ? 1 : 0;
            const noty = new Noty({
                timeout: 2000,
            });
            $.ajax({
                url: "{{ route("dashboard.{$route}.toggle", ':recordId') }}".replace(':recordId', recordId),
                type: "POST",
                data: {
                    property: property,
                    value: value,
                    _token: "{{ csrf_token() }}"
                },
                success: function(response) {
                    noty.push({
                        text: response.message,
                        type: 'success',
                    });

                },
                error: function(error) {
                    console.log(error);
                    noty.push({
                        text: error.responseJSON.message,
                        type: 'error',
                    });
                }
            });
        });

    </script>
@endpush